name: ARM Template Build and Test

on: 
  push:
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  build_and_test:
    name: Build ARM JSON Template
    runs-on: ubuntu-latest

    steps:
    # Check out
    - name: Checkout the repo
      uses: actions/checkout@v2

    # Runs the bicep CLI action - individual files
    - name: Run Bicep build
      uses: aliencube/bicep-build-actions@v0.3
      with:
        files: main.bicep

    # Checks the result
    - name: The job has succeeded
      if: ${{ success() }}
